trigger:
  branches:
    include:
      - main
  paths:
    include:
      - HandsOn/*
      - pipelines/frontend/*

pool:
  name: ExpensesReportPool # The agent pool you're using for the release

variables:
  # Define the working directory
  buildDirectory: "$(Build.SourcesDirectory)/HandsOn"

steps:
  # Step 1: Install dependencies using npm or yarn
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x" # Ensure the Node version is compatible with your Nx project
    displayName: "Install Node.js"

  - script: |
      npm install
    workingDirectory: $(buildDirectory)
    displayName: "Install dependencies and build"

  # Step 2: Build the Nx project
  - script: |
      npm run build
    workingDirectory: $(buildDirectory)
    displayName: "Build Nx Project"

  # Step 3: Deploy to Windows Server 2022 (Self-Hosted)
  # Make sure to replace 'deployPath' and the commands with actual deployment steps
  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(buildDirectory)/dist/farm/browser"
      TargetFolder: 'C:\\handson\\html' # Path on the self-hosted Windows server
      Overwrite: true
    displayName: "Copy Build Files to Server"

  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        Restart-Service -Name 'nginx'
    displayName: "Deploy to Windows Server 2022"
# Optional: Add notifications or additional tasks
